### ISSUE TITLE
Look into implementing multiplayer

### ISSUE THREAD

**Issue by carllei** [pqbyte/temp-name-game#38]
We should look into implementing multiplayer. Research has to be done to evaluate the difficulty of its implementation. We have previously discussed using Google Play Games services.

**Comment by tonikarppi** [comment]
I'll try to get a working example today. If I can't get it working I'll just do #19.

**Comment by tonikarppi** [comment]
I looked into Google Play Game Services, but it feels like it will be too much of a pain to implement it into the game since it would be too much of a hassle. Having to create "testing" google accounts and running multiple emulators (which needed Google Play installed) felt like it would take a lot of time. And all that's after having to manually add libraries from their testing directories. For now multiplayer is scrapped, I'll just implement some kind of an AI
